### ISSUE TITLE
Using unconditional pertrained weight to train a conditional model

### ISSUE THREAD

**Issue by hasaki321** [Asduffo/FreeGress#1]
Hello,
Thank you for your great work!

Have you tried to train the conditional model based on the pertrained weight of the unconditional model? How does it performs? 
How much worser would it be than training the conditional model from scratch?

Thank you.

**Comment by Asduffo** [comment]
Good evening
Thank you very much for your kind words, I appreciate it.

We did not perform any experiment using a pretrained, unconditional model as a base. Like with other pretrained models, we would need to add extra weights to account for the additional input (the conditioning vector). I am personally interested in personalizing generalized models with additional concepts, which is a closely related topic, so I may try and do some research on this matter in the future.

**Comment by hasaki321** [comment]
Thank you for your reply

**Comment by hasaki321** [comment]
Hello! Could you please provide the checkpoint for both uncondition training and condition on ZINC250k? Thank you so much!

**Comment by Asduffo** [comment]
Hello, and sorry for the late reply.

I do not have the checkpoints anymore. I could compute them again but right now the computational resources I have at my disposal are employed for another project that may take 4-5 months to finish. If you want, I can try and see if I still have the commands employed to launch the training

**Comment by hasaki321** [comment]
Thanks, I have already get an unconditional checkpoint on ZINK250k with your code train_uncondition.py. Is that correct for training an unconditional model? The validity for unconditional training of DiGress reach around 88.5% after training 300 epoches, which is a little bit higher than the result in your paper.

**Comment by Asduffo** [comment]
Yes, train_unconditional.py is the correct method. Your results could be due to many things that I can not evaluate without the full list of hyperparameters you used (it may also be a simple matter of different RNGs)
